# Generated by Django 5.2.7 on 2025-10-17 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.CharField(max_length=20, unique=True)),
                ("bus_name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_contact", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name="busschedule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="busschedule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="route",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="route",
            name="estimated_duration",
        ),
        migrations.RemoveField(
            model_name="route",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="route",
            name="total_distance",
        ),
        migrations.AddField(
            model_name="route",
            name="estimated_time",
            field=models.IntegerField(default=0, help_text="Estimated time in minutes"),
        ),
        migrations.AddField(
            model_name="route",
            name="stops",
            field=models.TextField(
                blank=True, default="", help_text="Comma separated list of stops"
            ),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buses.route"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buses.bus"
            ),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buses.busschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RouteStop",
        ),
        migrations.RemoveField(
            model_name="busschedule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="busschedule",
            name="days_of_week",
        ),
        migrations.RemoveField(
            model_name="busschedule",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="busschedule",
            name="updated_at",
        ),
    ]
