# Generated by Django 5.2.7 on 2025-10-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_bus_alter_busschedule_options_alter_route_options_and_more"),
        ("tracking", "0002_alter_buslocation_bus_alter_busstatus_bus_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Buses",
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("user", "schedule")},
        ),
    ]
