# Generated by Django 5.2.7 on 2025-10-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_bus_alter_busschedule_options_alter_route_options_and_more"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buslocation",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="buses.bus",
            ),
        ),
        migrations.AlterField(
            model_name="busstatus",
            name="bus",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_status",
                to="buses.bus",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="buses.bus",
            ),
        ),
    ]
